version: '3.8'

services:
  chatastrophe-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    env_file:
      - ./.env
    environment:
      - FLASK_APP=chatastrophe_api.py
    restart: unless-stopped
    networks:
      - chatastrophe-network

networks:
  chatastrophe-network:
    driver: bridge 